Repository carrot-kpi/reality-eth-v3-oracle-template, pull requests merged in 2023-03, with the labels that each got.

#2 First iteration of page component
  package.json
  packages/contracts/package.json
  packages/contracts/src/RealityV3Oracle.sol
  packages/frontend/package.json
  packages/frontend/src/abis/reality-eth-v3.json
  packages/frontend/src/commons/index.ts
  packages/frontend/src/creation-form/index.tsx
  packages/frontend/src/creation-form/types.ts
  packages/frontend/src/fetcher/abstraction/index.ts
  packages/frontend/src/fetcher/index.ts
  packages/frontend/src/fetcher/on-chain/index.ts
  packages/frontend/src/hooks/useWatchRealityQuestion.ts
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/bond-input/index.tsx
  packages/frontend/src/page/components/answer-form/common/styles.ts
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/pending-arbitration/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  packages/frontend/src/page/types.ts
  packages/frontend/src/utils/data-decoding.ts
  packages/frontend/src/utils/dates.ts
  packages/frontend/src/utils/index.ts
  yarn.lock
Labels: wip

#8 Implement pending state
  packages/frontend/package.json
  packages/frontend/src/assets/external.svg
  packages/frontend/src/commons/index.ts
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/opening-countdown/countdown-frame/index.tsx
  packages/frontend/src/page/components/opening-countdown/index.tsx
  packages/frontend/src/page/components/opening-countdown/vertical-divider/index.tsx
  packages/frontend/src/page/components/question-info/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  packages/frontend/src/utils/index.ts
  packages/frontend/tailwind.config.cjs
  packages/frontend/tsconfig.json
Labels: enhancement

#9 Refactor reality form
  packages/frontend/package.json
  packages/frontend/src/commons/index.ts
  packages/frontend/src/creation-form/index.tsx
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/bond-input/index.tsx
  packages/frontend/src/page/components/answer-form/common/styles.ts
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/learn-more/index.tsx
  packages/frontend/src/page/components/opening-countdown/countdown-frame/index.tsx
  packages/frontend/src/page/components/opening-countdown/index.tsx
  packages/frontend/src/page/components/pending-arbitration/index.tsx
  packages/frontend/src/page/components/question-info/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  packages/frontend/src/utils/index.ts
Labels: enhancement

#11 Reality page features
  packages/frontend/scripts/build.js
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/answer-info/index.tsx
  packages/frontend/src/page/components/learn-more/index.tsx
  packages/frontend/src/page/components/question-info/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/utils/index.ts
Labels: enhancement

#13 Add info popovers
  packages/frontend/package.json
  packages/frontend/src/page/components/answer-form/bond-input/index.tsx
  packages/frontend/src/page/components/answer-form/common/styles.ts
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/opening-countdown/countdown-frame/index.tsx
  packages/frontend/src/page/components/opening-countdown/index.tsx
  packages/frontend/src/page/components/opening-countdown/vertical-divider/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  yarn.lock
Labels: enhancement

#15 Finalize oracle
  packages/frontend/src/abis/reality-oracle-v3.json
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  yarn.lock
Labels: enhancement

#17 Arbitration request
  package.json
  packages/contracts/package.json
  packages/frontend/package.json
  packages/frontend/src/abis/trusted-reality-arbitrator-v3.json
  packages/frontend/src/commons/index.ts
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/pending-arbitration/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  packages/frontend/src/utils/index.ts
  yarn.lock
Labels: enhancement

#20 Add txs to account popover
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
  packages/frontend/src/utils/dates.ts
Labels: enhancement

#22 Fix bond input behavior
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/bond-input/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/answer-info/index.tsx
Labels: bug

#29 Claim and withdraw
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/arbitrator/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/components/question-info/index.tsx
  packages/frontend/src/page/i18n/en.json
Labels: enhancement

#31 Finalizing timer
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/i18n/en.json
Labels: enhancement

#32 feat(frontend): upgrade dependencies and adapt to new css scoping rules
  package.json
  packages/contracts/package.json
  packages/eslint-config-custom/package.json
  packages/frontend/.cct/utils/get-template-component-webpack-config.js
  packages/frontend/package.json
  packages/frontend/src/creation-form/index.tsx
  packages/frontend/src/hooks/useQuestionContent.ts
  packages/frontend/src/page/index.tsx
  yarn.lock
Labels: wip

#33 Warning when KPI token is expired
  packages/frontend/src/assets/danger.svg
  packages/frontend/src/page/components/answer-form/answer/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
  packages/frontend/src/page/i18n/en.json
  packages/frontend/src/page/index.tsx
Labels: enhancement

#35 Prevent error when min bond is not a valid number
  packages/frontend/src/creation-form/index.tsx
  packages/frontend/src/page/components/answer-form/index.tsx
Labels: bug
